### PR TITLE
[product.h] added template into friend declaration to prevent show warning -Wno-non-template-friend

### PR DESCRIPTION
**Pull request by TheVice**
Hello.

To prevent showing warning Wno-non-template-friend from product.h I propose this changes.
As reference and explanation used [this](http://www.cplusplus.com/forum/general/23865/#msg125445).

Thank you.

### CODE REVIEW

**Comment by PkXwmpgN** [comment]
Hello.

It is not the same things. I think the fix should be
```
template<typename _Type, _Type _Default>
class product
{
    ...
    friend bool operator==(const product & l, const product & r)
    {
        return l.value_ == r.value_;
    }
    friend bool operator!=(const product & l, const product & r)
    {
        return !(l == r);
    }
...
};
```

We need to move the friends definition. The same approach is used the [values class](https://github.com/PkXwmpgN/elements/blob/master/elements/utils/std/values.h).
For more information this [article](http://web.mst.edu/~nmjxv3/articles/templates.html). What do you think?

Thank you.

**Comment by TheVice** [comment]
Hello.

Yes, I agree that for similar cases should use same approach.
I update change by moving definition.

Thank you.

**Comment by PkXwmpgN** [comment]
Great!

For some reasons I don't use merge and use rebase. Could you please squash your changes?
Then I cherry-pick this to the master branch.

Thank you.

**Comment by TheVice** [comment]
No problem.

By the way same result if use soft reset to last master commit and create new commit for product branch. When pushed also force should be used.

Thank you.

**Comment by PkXwmpgN** [comment]
50th commit :)

Thank you.

**Pull request closed without merging**
